
enum SortType {
 ASCENDING
 DESCENDING
}

type Person {
  name:String!
  age:Int
  friends( named: [String] = ["default_joe", "default_suzie"],
           id: ID=null,
           has_id: Boolean = false,
           blk_str: String = """A block " "\" " quote!!""" ,
           str : String = "Hello World" ,
           e : ASCENDING ,
           obj: Person = { "key":[ ASCENDING, 3.5e-3, false ], "def":null },
           sort_order:SortType = DESCENDING ):[Person]
}
