enum ContentModuleType 
{
  POLL
  TASKLIST
}

type TaskListModule {
  content_type: ContentModuleType!
  tasklist_id: ID!
}

type PollModule {
  content_type: ContentModuleType!
  poll_id: ID!
}

union ContentModule = PollModule | TaskListModule

type Query
{
   content_module_by_id(id: ID!): ContentModule!
}

query GetContentModuleById($id: ID!) {
  content_module_by_id(id: $id) {
    __typename
    ... on TaskListModule {
      content_type
      tasklist_id
    }
    ... on PollModule {
      content_type
      poll_id
    }
  }
}
